services:
  mysql-db:
    image: mysql:9.0
    container_name: fooddelivery-mysql
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: fooddelivery_db
    volumes:
      - mysql_data:/var/lib/mysql
    command: --innodb-buffer-pool-size=64M --max-connections=50
    # Thêm giới hạn cho MySQL
    deploy:
      resources:
        limits:
          memory: 300M

  redis-db:
    image: redis:7-alpine
    container_name: fooddelivery-redis
    restart: always
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 100M

  backend-app:
    build: .
    image: ikenuyh/fooddelivery-backend:latest
    container_name: fooddelivery-backend-app
    restart: always
    ports:
      - "8083:8081"
    depends_on:
      - mysql-db
      - redis-db
      - elasticsearch
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/fooddelivery_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_REDIS_HOST=redis-db
      - SPRING_REDIS_PORT=6379
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
    # Thêm giới hạn cho Backend
    deploy:
      resources:
        limits:
          memory: 512M

  reverse-proxy:
    image: caddy:2-alpine
    container_name: fooddelivery-caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.0
    container_name: fooddelivery-es
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      # Thêm biến này để bóp nghẹt RAM của Elasticsearch xuống 256MB
      - ES_JAVA_OPTS="-Xms256m -Xmx256m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    # Thêm giới hạn phần cứng
    deploy:
      resources:
        limits:
          memory: 400M

volumes:
  mysql_data:
  caddy_data:
  caddy_config:
  es_data: