services:
  mysql-db:
    image: mysql:9.0
    container_name: fooddelivery-mysql
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: fooddelivery_db
    volumes:
      - mysql_data:/var/lib/mysql

  redis-db:
    image: redis:7-alpine
    container_name: fooddelivery-redis
    restart: always
    ports:
      - "6379:6379"

  backend-app:
    image: ikenuyh/fooddelivery-backend:latest
    container_name: fooddelivery-backend-app
    restart: always
    ports:
      - "8083:8081"
    depends_on:
      - mysql-db
      - redis-db
    environment:
      # Ket noi voi MySQL thong qua ten service
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/fooddelivery_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_REDIS_HOST=redis-db # Link tới Redis
      - SPRING_REDIS_PORT=6379

  # Them Caddy de lo vu HTTPS
  reverse-proxy:
    image: caddy:2-alpine
    container_name: fooddelivery-caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: fooddelivery-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

volumes:
  mysql_data:
  caddy_data:
  caddy_config: