spring:
  datasource:
    url: jdbc:mysql://localhost:3308/fooddelivery_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: "123456"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    out-of-order: false
    table: flyway_schema_history

  output:
    ansi:
      enabled: always

  elasticsearch:
    uris: http://localhost:9200

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:no-reply@fooddelivery.com}
    password: ${MAIL_PASSWORD:dummy}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8081

cloudinary:
  cloud-name: "dkm39i1z8"
  api-key: "392638882274686"
  api-secret: "M4row-OumipTXq-Nqn8mUdZMs4Y"

jwt:
  secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
  expiration: 86400000 # 1 ngay

zalopay:
  app-id: "2553"
  key1: "PcY4iZIKFCIdgZvA6ueMcMHHUbRLYjPL"
  key2: "kLtgPl8YESD1XcgX5IZz2eOMEs7A2e1O"
  endpoint-create: "https://sb-openapi.zalopay.vn/v2/create"
  endpoint-query: "https://sb-openapi.zalopay.vn/v2/query"
  endpoint-refund: "https://sb-openapi.zalopay.vn/v2/refund"
  endpoint-query-refund: "https://sb-openapi.zalopay.vn/v2/query_refund"